export const RESOURCE_LOADSTART = 'RESOURCE_LOADSTART';
export const RESOURCE_LOAD = 'RESOURCE_LOAD';
export const RESOURCE_ERROR = 'RESOURCE_ERROR';
export const RESOURCE_PROGRESS = 'RESOURCE_PROGRESS';
export const RESOURCE_TIMEOUT = 'RESOURCE_TIMEOUT';

export const IMAGE_LOADSTART = 'IMAGE_LOADSTART';
export const IMAGE_LOAD = 'IMAGE_LOAD';
export const IMAGE_ERROR = 'IMAGE_ERROR';
export const IMAGE_PROGRESS = 'IMAGE_PROGRESS';
export const IMAGE_TIMEOUT = 'IMAGE_TIMEOUT';

export const EXTRACT = 'EXTRACT';
export const PREPARE = 'PREPARE';
export const DOWNLOAD = 'DOWNLOAD';
export const INITIALIZE = 'INITIALIZE';