export const EXTRACT = 'EXTRACT';
export const PREPARE = 'PREPARE';
export const DOWNLOAD = 'DOWNLOAD';
export const INITIALIZE = 'INITIALIZE';

export const CHAPTER_SELECT = 'CHAPTER_SELECT';

export const EXTRACT_STATE_CHANGE = 'EXTRACT_STATE_CHANGE';
export const DOWNLOAD_STATE_CHANGE = 'DOWNLOAD_STATE_CHANGE'